directories:
    data: ~/incasem/data

prediction:
    pipeline: baseline
    data: 
    run_id_training: 
    checkpoint:
    directories:
        prefix: ~/incasem/data
    input_size_voxels: [204, 204, 204]
    output_size_voxels: [110, 110, 110]
    num_workers: 8
    log_metrics: False
    torch:
        device: 0
